<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="ravi" failures="1" tests="2" name="Default test(failed)" time="0.07" errors="0" timestamp="2025-08-10T11:14:06 IST">
  <testcase classname="day2.Testannotation" name="skiipedtest" time="0.012">
    <skipped/>
  </testcase> <!-- skiipedtest -->
  <testcase classname="day2.Testannotation" name="btest" time="0.008">
    <failure type="java.lang.AssertionError" message="number are not matched expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: number are not matched expected [4] but found [2]
at day2.Testannotation.btest(Testannotation.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- btest -->
  <testcase classname="day2.Testannotation" name="ctest" time="0.0">
    <ignored/>
  </testcase> <!-- ctest -->
  <testcase classname="day2.Testannotation" name="enterinput" time="0.0">
    <ignored/>
  </testcase> <!-- enterinput -->
  <testcase classname="day2.Testannotation" name="atest3" time="0.0">
    <ignored/>
  </testcase> <!-- atest3 -->
  <testcase classname="day2.Testannotation" name="enterinput1" time="0.0">
    <ignored/>
  </testcase> <!-- enterinput1 -->
  <testcase classname="day2.Testannotation" name="calcuate" time="0.0">
    <ignored/>
  </testcase> <!-- calcuate -->
</testsuite> <!-- Default test(failed) -->
